### ISSUE TITLE
Change the height with percentage values.

### ISSUE THREAD

**Issue by oxsav** [kenshoo/react-multi-select#102]
I'm trying to change the height of the area that is scrollable. In my case what fits for me is to pass a % value, is that possible? Could that be done? Or should be better to the component accept a style prop and pass the style inside the component.

The wrapperClassName prop does not work, because to change the height, with that prop, I have to use the _!important_ tag in CSS and even though only the height of the box is changed, not the height of the scrollable list.

<img width="497" alt="captura de ecra 2018-09-20 as 15 31 17" src="https://user-images.githubusercontent.com/2349816/45825743-dbc09280-bcea-11e8-9846-b7e0b95eb387.png">

**Comment by PeterShershov** [comment]
Hey, looking into this. 
Thanks for reporting :+1:

**Comment by PeterShershov** [comment]
Hey, 
We will hopefully address this issue around November 11th.

@oxsav

**Comment by omerkenshoo** [comment]
Hi @oxsav,

There is a property ``height`` to the component that can receive a string with percentage
I will add a story with an example soon

**Comment by omerkenshoo** [comment]
Right, using percetnage ``height`` property will not work because there are calculations inside the component

Looking into it

**Comment by omerkenshoo** [comment]
Added a new prop: ``responsiveHeight``
https://github.com/kenshoo/react-multi-select/pull/112
