### ISSUE TITLE
Using MutliSelect in a custom component library and importing it in another project causes an export error

### ISSUE THREAD

**Issue by asher-scott** [kenshoo/react-multi-select#103]
I'm currently creating a custom component library that contains a component that uses the MultiSelect component.  In my component library I have an example react project that I use to test the components I write.  When I use the custom component in the example project, it works properly.  Once I am done testing the components in the example, I bundle the library using rollup.js and publish the library to an npm registry on MyGet so I can install the library in any other project where I might want to use it.  Now, when I install that published npm package in a different project and try to use the custom component, I am getting errors when I try to use the custom component that uses MultiSelect.

Here's some visuals to aid in my explaination:

This is the initial component view:

![capture2](https://user-images.githubusercontent.com/9473620/46078301-bb1c9080-c161-11e8-866d-2911a306559a.PNG)

Now when I click the manage button, the view inside the card should switch to the MultiSelect component like this (Note this screenshot is taken from the example app within my component library):

![capture3](https://user-images.githubusercontent.com/9473620/46078689-dc31b100-c162-11e8-9537-f6de8096de9d.PNG)

However, when I try to click the manage button when the component is imported in another application, it crashes and gives me console errors like so:
![capture](https://user-images.githubusercontent.com/9473620/46077984-c1f6d380-c160-11e8-9d4f-27f4a58d54d9.PNG)

After searching the internet for a while, it seems that the errors are rooted in improperly exporting or importing defaults from modules.

I tried exporting a very small component that simply rendered the MultiSelect component along with a header tag to see if it was something other than the MultiSelect that was causing the errors, but even the small rudimentary example caused the same issues.

I'm wondering if this is an issue with how the MultiSelect component is exported in the build process, or if its me being oblivious to something in my bundling process.

**Comment by PeterShershov** [comment]
Hey @asher-scott, when publishing, are you making sure that `react` and `react-dom` are externals (not included in the bundle)? 
We do the same with Webpack: https://github.com/kenshoo/react-multi-select/blob/master/config/webpack/webpack.common.js#L8

That could be a possible reason.
In addition, make sure that `react` and `react-dom` are set as a peer dependency (not dependencies) in your `package.json`.

**Comment by asher-scott** [comment]
@PeterShershov Thanks for the fast response, I appreciate it greatly!  I was missing `react-dom` in my peer dependencies, so I added that, and then I added `react` and `react-dom` to my externals in my rollup.config.js.  I'm not sure how closely related the build processes of Rollup and Webpack are to one another, but I published the bundle and the same errors remain.

This is my rollup.config.js file:
https://gist.github.com/asher-scott/66f769477e0e6da9fece90f9e7deec6e

and my package.json file:
https://gist.github.com/asher-scott/e3e5354eed0f062c196d86cded15fb56

I have other components in my component library that use external libraries and they render fine, its only the one with MutliSelect that's having a hard time.  If it helps more I can try and whip up a smaller example and report back to you with some code to look at.

Again, I greatly appreciate you help and timely response!

**Comment by PeterShershov** [comment]
Any example that reproduces the issue would be very useful. 

I noticed you're using Typecript. 
Can you also share your tsconfig (is esModuleInterop turned on)?

**Comment by asher-scott** [comment]
Here is my current tsconfig:
```
{
    "compilerOptions": {
        "outDir": "./build",
        "sourceMap": true,
        "noImplicitAny": true,
        "module": "es6",
        "target": "es5",
        "jsx": "react",
        "allowJs": true,
        "noUnusedLocals": true
    }
}
```
esModuleInterop is not turned on.... I'll give it a shot

**Comment by asher-scott** [comment]
esModuleInterop didn't seem to help.  I'll try to create a slim example of the issue and report back with more details.  I might even find my problem in doing so.

**Comment by PeterShershov** [comment]
Great, waiting to hear from you

**Comment by asher-scott** [comment]
@PeterShershov I wrote up a very small component library example that mimics my development environment and build process.  You can see that code here: https://github.com/asher-scott/test-multi-select

If you want to reproduce the error that I am getting, you can do an `npm publish` on the project and publish it to an npm registry (I used MyGet).  If you then `npm install` the package that you published in a react application (I tested with create-react-app) and try to import the TestMultiSelect component and render it in the application you will see the error that I have been running into.

If I can provide any more details, I'd be happy to do so.  Thanks!

**Comment by PeterShershov** [comment]
@asher-scott Thanks! I'll take a look

**Comment by asher-scott** [comment]
Awesome thank you!

**Comment by PeterShershov** [comment]
Hey, sorry for not updating you about this.
We will hopefully address this issue around November 11th.

@asher-scott

**Comment by asher-scott** [comment]
@PeterShershov Not a problem, I understand!  I appreciate you letting me know!

**Comment by asher-scott** [comment]
@PeterShershov I may have figured out why I was running into the error that I reported.  It appears that I needed to declare your multi select component as an external library in my rollup.config.js file.

From what I can see so far, everything is working fine after making the proper modification to my rollup configuration:

```
export default {
    input: 'src/index.ts',
    output: {
        file: 'dist/bundle.js',
        format: 'cjs'
    },
    external: ['@kenshooui/react-multi-select'],
    ...
}
```

**Comment by liorheber** [comment]
@asher-scott I hope everything os working fine for you.
I'm closing this issue for now, please feel free to reopen it if you require any more assistance.
