### ISSUE TITLE
I ported this to use blueprintjs  

### ISSUE THREAD

**Issue by tnrich** [kenshoo/react-multi-select#107]
In case anyone is interested, I ported this component to use blueprintjs  (https://github.com/palantir/blueprint)

A demo can be seen here:
https://teselagen.github.io/teselagen-react-components/#/MultiSelectSideBySide

https://github.com/TeselaGen/teselagen-react-components

You can close this whenever you want @kenshoo . Thanks for making this great component.

**Comment by uikenshoo** [comment]
@tnrich it is very exciting to see our component being used out there.
We hope that we will be able to provide additional components in the near future and would be excited to see you contribute to the project in the future.

Thanks again for sharing this with us!
