### ISSUE TITLE
Changing item label

### ISSUE THREAD

**Issue by AntonOellerer** [kenshoo/react-multi-select#111]
Hey, 
While working with this library, I encountered a problem I have when feeding the component with data from a server. As far as I can tell, right now it is not possible to change the name of the label key via custom properties, which means one has to iterate through all the data to rename the label key. Because of this here my two questions:

* Is it currently possible to change the name of the property providing the label?
* If not, would it be feasible/would it make sense to implement for this project?

I hope this question is in line with the guidelines, thank you for your great work.
Regards
Antno

**Comment by uikenshoo** [comment]
Hi @AntonOellerer thank you very much for using our component.
react-multi-select allows you to customize the data structure as you please by allowing you to override the ItemRenderer and the filterFunction.
You can go over the readme file to read on their interface but basically the ItemRendeder currently uses the label for the display and the filterFunction to filter based on the label.
You could basically replace these two to support any object structure of your liking.

Alternatively, we encourage you to contribute an enhancement for the component that could allow you to stick to the default renderers and methods.
An idea I could think of is a prop for itemMapping that could be used both in the filter and the renderer when provided.

I hope my answer makes sense to you.
Feel free to followup if you need any further assistance.
