### ISSUE TITLE
Prop Type - Prop Validators Error

### ISSUE THREAD

**Issue by engineer-only** [kenshoo/react-multi-select#120]
I use this module in order to create a multi selectable box which is populated by user's contacts. When contacts are selected, new chat group with the selected ones is created and so on.

However when I only just install the package following the steps in the 

[Official Page](https://www.npmjs.com/package/@kenshooui/react-multi-select)

and insert the component as following (same with the demo)

```
      <MultiSelect
        items={items}
        selectedItems={selectedItems}
        onChange={this.handleChange}
      />
```

I got the following error : 

```
index.js:1452 Warning: Failed prop type: Calling PropTypes validators directly is not supported by the `prop-types` package. Use PropTypes.checkPropTypes() to call them. Read more at http://fb.me/use-check-prop-types
    in t (created by n)
    in n (at Contacts.jsx:103)
    in div (at Contacts.jsx:101)
```

After my research I learned that, it is caused because React and/or Redux version. Is there such a compatibility problem right now? If not how can I overcome the situation?

**Comment by talyak** [comment]
@engineer-only - which version of react do you use?
