### ISSUE TITLE
Keycode onChange

### ISSUE THREAD

**Issue by Cozloschi** [kenshoo/react-multi-select#122]
Hello,
I would like to cancel the real time filtering and to be able to listen to 'Enter' keyCode in onChange event, in order to do a backend filtering. I tried creating my own search component and to pass it to searchRenderer component, but I've ended up doing all sorts of hacks to be able to get the keyCode ( E.g: onKeyPress={event => {event.target.value = event.key; return props.onChange(event)}} ) since you're always trying to get value from **event.target.value**. But even so, every time I change the component **searchValue** props, the search input loses focus.

Is there any way to solve this?

P.S: I am using the latest version of react-multi-select ( 1.0.64 )

Also I've noticed that event if I provide a **searchValue** value on element mount, the value does not appear in the default search box

Thank you in advance.

**Comment by liorheber** [comment]
Hello,
Please refer to https://github.com/kenshoo/react-multi-select#search-function and see if this provides the solution you need.

**Comment by Cozloschi** [comment]
That was the answer! Thank you for that.
