### ISSUE TITLE
Should be a way to pass onClick function to itemRenderer instead of making whole item clickable ?

### ISSUE THREAD

**Issue by jaspreet963** [kenshoo/react-multi-select#125]
## Expected Behavior
By default, whole item is clickable and click further toggles the selection/checkbox. Same behaviour can be observed for custom item (via itemRenderer).

## Actual Behavior
There should be a way to pass onClick method to props as well. One might want to toggle selection only on checkbox click or on particular div/element.

## Steps to Reproduce the Problem
  1. Add custom item using item renderer.
  2. By default whole item is clickable and toggles selection even if I want to keep only particular part of it clickable.
  3. In my case, I have used star rating in dropdown items. Now, if I change rating from 4 to 5, it de-selects the checkbox.

## Specifications

  - Version: 1.0.64

**Comment by liorheber** [comment]
Hi @jaspreet963 ,
The item interface contains the onClick method.
This should mean that something along this line should work:
```
const item = ({
  item,
  height,
  onClick,
  withBorder,
  group,
  checked,
  indeterminate,
  disabled
}) => (
  <div>
    <Checkbox onClick={onClick} />
    <Dropdown item={item}/>
  <div>
)
```
If this is what you're doing and you're still triggering the onClick event from the dropdown, could you please share an example?

**Comment by liorheber** [comment]
Hi,

Closing this, please feel free to re-open if you need more assistance.
