### ISSUE TITLE
I wan to put border outside all the items, which should not include search bar. Is there any way to do it?

### ISSUE THREAD

**Issue by puneet24** [kenshoo/react-multi-select#131]
## Steps to Reproduce the Problem

  1.
  1.
  1.

## Specifications

  - Version:
  - Platform:
  - Subsystem:

**Comment by liorheber** [comment]
Hi @puneet24 
I'm not sure I fully understood your question. Could you please further explain?

If you're trying to remove the SearchBar you have the showSearch prop which you can pass false to.

**Comment by puneet24** [comment]
I want to render all the items in a container having some border. Is it possible with this library?

**Comment by talyak** [comment]
@puneet24 - you can use the listRenderer prop to set (border) styling for the items container. if you want to include the select all inside this border use also SelectAllRenderer prop.
You can see example how to use it in the "Carousel Multi Select" section of the storybook.

**Comment by talyak** [comment]
@puneet24 - any updates? did it help you? can I close this issue?
