### ISSUE TITLE
Versions after 1.0.68 make MultiSelect unusable

### ISSUE THREAD

**Issue by AntonOellerer** [kenshoo/react-multi-select#152]
## Expected Behavior
When updating from react-multi-select 1.0.68 to 1.0.69, there should not be any big changes

![Captura de pantalla de 2019-05-20 15-55-30](https://user-images.githubusercontent.com/13524304/58026855-b739e600-7b17-11e9-9af1-867b378eb04b.png)

## Actual Behavior
The `MultiSelect` component does not render correctly and overlays buttons under it (on the y-axis)

![Captura de pantalla de 2019-05-20 15-53-06](https://user-images.githubusercontent.com/13524304/58026734-69bd7900-7b17-11e9-8d13-4900b56ca13f.png)

## Steps to Reproduce the Problem

  Other people seem to not have this problem, so here are the `package.json` dependencies
```
    "@kenshooui/react-multi-select": "1.0.69",
    "axios": "^0.17.1",
    "body-parser": "^1.18.3",
    "express": "^4.16.3",
    "moment": "latest",
    "njwt": "^1.0.0",
    "react": "^16.4.0",
    "react-copy-to-clipboard": "^5.0.1",
    "react-datepicker": "^0.61.0",
    "react-dom": "^16.1.1",
    "react-modal": "^3.8.1",
    "react-numeric-input": "^2.2.3",
    "react-scripts": "^3.0.1",
    "react-select": "^1.1.0",
    "react-table": "^6.7.4"
```

## Specifications

  - Version: 1.0.69
  - Platform: Linux
  - Subsystem: Fedora

**Comment by MaksimDrobchak** [comment]
Hi! Sorry but after version 1.0.68 you need `import "@kenshooui/react-multi-select/dist/style.css"`
for supporting native style multi-column-select (it was specified in readme  earlier).
