### ISSUE TITLE
Integrate with react + typescipt

### ISSUE THREAD

**Issue by tynarbekov** [kenshoo/react-multi-select#153]
I have a project react+typescript.
As I right understood, this package doesn't have typescript support.
And I create type like this.
In Component importing like this:
```
import * as React from 'react'
import {WithTheme} from '../..'
import {MultiSelect} from '@kenshooui/react-multi-select'
import '@kenshooui/react-multi-select/dist/style.css'
import withTheme from '../../theme/withTheme'

interface MultiSelectComponentProps extends WithTheme {
  some: string
}

export class MultiSelectComponent extends React.Component<MultiSelectComponentProps> {
  render() {
    const items = [
      {id: 0, label: 'item0'},
      {id: 1, label: 'item1'},
      {id: 2, label: 'item2'}
      ]

    const selectedItems: Array<{id: number, label: string}> = []

    return (
      <MultiSelect
        items={items}
        selectedItems={selectedItems}
        onChange={this.handleChange}
      />
    )
  }

  // tslint:disable no-any
  handleChange = (values: any) => {
    console.log(values)
  }
}
export default withTheme(MultiSelectComponent)

```
And declare module like this
```

declare module '@kenshooui/react-multi-select' {
  import * as React from 'react'
  export class MultiSelect extends React.Component<any> {}
}
```

`
And I have error like this:
Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in, or you might have mixed up default and named imports.

Check the render method of `MultiSelectComponent`.`
`
But if I render `<div>Hello</div>`, it's work

**Comment by omerkenshoo** [comment]
Hi @tynarbekov,
Sorry for the late reply.

It seems like your usage was wrong:
```import {MultiSelect} from '@kenshooui/react-multi-select'```

Take of the curly brackets and it should work:
```import MultiSelect from "@kenshooui/react-multi-select";```
