### ISSUE TITLE
Selected items in search place

### ISSUE THREAD

**Issue by tynarbekov** [kenshoo/react-multi-select#154]
It's is possible render selected items in 'Search' place?

**Comment by stepovat** [comment]
Hi @tynarbekov, 
sorry, but not sure I fully understand
can you please provide more details about the problem you have?
If you add example of your problem - it will be even better

Thanks!

**Comment by liorheber** [comment]
@tynarbekov I am closing the issue.
Please feel free to reopen when you are able to provide more information.

Thanks.
