### ISSUE TITLE
Production bundle is missing a few areas

### ISSUE THREAD

**Issue by liorheber** [kenshoo/react-multi-select#46]
When using the component in production some parts of it are missing:
1. Select all is missing
2. selection text is undefined undefined
3. clear all is missing
4. placement is a bit off

![image](https://user-images.githubusercontent.com/4344533/37752123-ea54a9e8-2d9e-11e8-82ea-4b427e16788d.png)

**Comment by liorheber** [comment]
@AmirAsaraf could you please take a look at this?

**Comment by AmirAsaraf** [comment]
@liorheber on it
