### ISSUE TITLE
X icon is not aligned correctly

### ISSUE THREAD

**Issue by liorheber** [kenshoo/react-multi-select#61]
## Expected Behavior
X icon in the selected items should be aligned to the clear all test.

## Actual Behavior
![image](https://user-images.githubusercontent.com/4344533/37862152-68cda796-2f59-11e8-9f60-65b8fadd5a14.png)

## Steps to Reproduce the Problem

  1. Select an item.

## Specifications

  - Version: 1.0.36

**Comment by ganes1410** [comment]
i will take this up @liorheber
