### ISSUE TITLE
Not able to remove Selected list table

### ISSUE THREAD

**Issue by sumanth234** [kenshoo/react-multi-select#71]
## Expected Behavior

Is there any option to remove selected list table.

## Actual Behavior

We are able to remove Search and selected all option, but not selected list table.

**Comment by liorheber** [comment]
We could add the feature but could please you explain the use-case?

**Comment by liorheber** [comment]
Like this?
![image](https://user-images.githubusercontent.com/4344533/37988514-c6ecc994-3209-11e8-8b89-0702e506e755.png)

**Comment by AmirAsaraf** [comment]
It's quite simple to add support for it

**Comment by liorheber** [comment]
Do you want to take it @AmirAsaraf ?

**Comment by AmirAsaraf** [comment]
Yup

**Comment by liorheber** [comment]
@sumanth234 amir added your feature request under the prop showSelectedItems
