### ISSUE TITLE
The X icon doesn't remain when the text is too long

### ISSUE THREAD

**Issue by michalsabag** [kenshoo/react-multi-select#83]
## Expected Behavior
The X icon in selected items will remain even if the text is too long

## Actual Behavior
The X icon doesn't remain when the text is too long

## Steps to Reproduce the Problem

  1. put long string in the item label
  2. move it to selected list
  3. check if X icon exist

**Comment by liorheber** [comment]
How are we planning to solve this? overflow: ellipsis?

**Comment by AmirAsaraf** [comment]
When elipsis is applied we should also show tooltip

**Comment by AmirAsaraf** [comment]
I'm working on elipsis with tooltip. Currently we are doing it on the itemRenderer in creation flow. I can do it if it will be relevant
![image](https://user-images.githubusercontent.com/12827272/39302037-f4edf87e-4959-11e8-88af-a18f3e120933.png)

**Comment by liorheber** [comment]
Thanks, @michalsabag already issued a PR for this:
https://github.com/kenshoo/react-multi-select/pull/84

**Comment by AmirAsaraf** [comment]
Sure
